//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3634
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaptiveAccountsSampleApp {
    
    public partial class SetFundingSourcesConfirmed {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.WebControls.Button AdaptiveAccountsBtn;
    }
}
